/**
 * Created by Guillaume on 26.06.2016.
 */

var config = {

    DEFAULT_EXP_METHOD : true,
    DEFAULT_NUCL_CONSTRUCT_TIME : 7,
    DEFAULT_NUCL_LIFETIME : 50,
    DEFAULT_NUCL_POWER : 1000,
    DEFAULT_NUCL_UPTIME : 7000,

    DEFAULT_GAZ_CONSTRUCT_TIME : 3,
    DEFAULT_GAZ_LIFETIME : 20,
    DEFAULT_GAZ_POWER : 400,
    DEFAULT_GAZ_UPTIME : 4000,

    DEFAULT_HYDRO_ACC_EVOLUTION :  0,
    DEFAULT_HYDRO_FIL_EVOLUTION :  0,
    DEFAULT_HYDRO_SOLAR_EVOLUTION :  0,
    DEFAULT_HYDRO_EOL_EVOLUTION :  0,
    DEFAULT_HYDRO_GEOTHERM_EVOLUTION :  0,

    DEFAULT_NUCL_PRICE :  5,
    DEFAULT_GAZ_PRICE :  6,
    DEFAULT_HYDRO_PRICE :  6,
    DEFAULT_EOL_PRICE :  7.5,
    DEFAULT_SOLAR_PRICE :  9,
    DEFAULT_IMPORT_PRICE :  7,

    DEFAULT_NUCL_POLLUTION :  23.6,
    DEFAULT_GAZ_POLLUTION :  670,
    DEFAULT_HYDRO_POLLUTION :  12.6 ,
    DEFAULT_EOL_POLLUTION :  26,
    DEFAULT_SOLAR_POLLUTION :  95,
    DEFAULT_IMPORT_POLLUTION :  522,
    DEFAULT_GEOTHERM_POLLUTION : 31,
    DEFAULT_COAL_POLLUTION : 1238
    
} ;
    
    
   